[package]
name = "octave-lsp-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octave-lsp = { version = "0.1.0", path = "../octave-lsp" }
